version: '2'
services:
  vsplunk:
    networks: 
      - nett
    image: busybox
    volumes:
      - /opt/splunk/etc
      - /opt/splunk/var

  splunk:
    networks: 
      - nett
    hostname: splunk
    image: mava/splunk:6.4.1
    environment:
      - SPLUNK_START_ARGS= --accept-license --answer-yes
      - SPLUNK_ENABLE_LISTEN=9997
    volumes_from:
      - vsplunk
    ports:
      - 8000:8000
      - 9997:9997
    expose:
      - 8000
    restart: always

networks:
  nett: {}
